permalink: /:categories/:title/
url: "https://nengwuzhi.github.io/"
full_name: "Saigon Jekyll Theme"
blog_title: "能无知"
author_img_name_path: "/images/users/user.jpg"
disqus_shortname: "example"
copyright_year: "2016"
google_analytics_code: ""
aboutme: "I like ramen noodles with cream."


# other links
twitter_username: 
facebook_username: xxxxxxx
github_username:  nengwuzhi
email: nengwuneng@126.com
weibo_username: nengwunao
Weixin_username: nengwuzhi
linkedIn_username: nengwuzhi
dribbble_username:


defaults:
  -
    scope:
      path: ""
      type: posts
    values:
      layout: blog
      styles : [_post.css]

# url
category_dir: category/
tag_dir: tag/
playlist_dir: /playlist/ || music
