permalink: /:categories/:title/
url: "https://nengwuzhi.github.io/"
full_name: "Saigon Jekyll Theme"
first_name: "Just"
last_name: "Me"
blog_title: "Title"
author_img_name_path: "/images/users/user.jpg"
disqus_shortname: "example"
copyright_year: "2016"
google_analytics_code: ""
aboutme: "I like ramen noodles with cream."


defaults:
  -
    scope:
      path: ""
      type: posts
    values:
      layout: blog
      styles : [_post.scss]

# url
category_dir: category/
tag_dir: tag/
